name: Juni CLI via Python
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/py-junie-cli.yml
jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install junie-cli
        run: npm install -g jetbrains/junie-cli

      #- name: Install junie-cli via Script
      #  run: curl -fsSL https://junie.jetbrains.com/install.sh | bash
      
      - name: Run Python Worker
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        run: python worker.py
